### ISSUE TITLE
Raspberry installation doesn’t work

### ISSUE THREAD

**Issue by choucous** [360manu/kettlerUSB2BLE#1]
Hi everybody,
I’m trying to install the daumUSB2BLE on a Raspberry zero w and a 3B with Stretch distribution. I used different Node.js version (from 8.x, 10.x , and above). Unfortunatly I have many errors about Dependecies, specialy with serial and usb node package.
Is there somebody able to help me and confirm that’s possible to install the DaumUSB2BLE on a Raspberry Pi.
In advance thank you.

**Comment by 360manu** [comment]
Hello

What instruction did you followed ?

Here is my installation list:

nodejs
https://github.com/sdesalas/node-pi-zero
**version lts**

BLE
https://github.com/olympum/waterrower-ble

bleno
https://github.com/noble/bleno

pour lancement auto :
sudo systemctl link /home/pi/KettlerUSB/kettler.service
-> Created symlink /etc/systemd/system/kettler.service → /home/pi/KettlerUSB/kettler.service.

sudo systemctl enable kettler.service
-> Created symlink /etc/systemd/system/multi-user.target.wants/kettler.service → /home/pi/KettlerUSB/kettler.service.

sudo systemctl start kettler.service

**Comment by weinzmi** [comment]
Hi all,

I’ve forked the kettlerUSB2BLE from 360manu and adopted it for DAUM
ergometers.

This is my first fork/project and it’s full of child issues, specially when
it comes to installing and taking care of dependencies on other packages.

To answer your question:

Yes it’s possible to run it on a RPi.
I’m running it on a RPi3 and RPi zero W.

I’ll try to update the dependencies and send you the versions I’m using on
my current working installations.

This will take some time since I’m on a business trip with no access to my
dev environment - one week minimum.

With best regards
Michael

**Comment by weinzmi** [comment]
quick update:

like I've said, beginner issues ;)

could access the RPi3 remotely:

pi@raspberrypi:~ $ node -v
v8.11.1

have a look at the "npm list" of my two directories:
  /home/pi/ergoFACE_BLE
  /home/pi




pi@raspberrypi:~ $ npm list
/home/pi/ergoFACE_BLE
├── @serialport/parser-inter-byte-timeout@1.1.0
├── angular@1.7.8
├── angularjs-gauge@2.2.0
├── bindings@1.2.1
├─┬ chart.js@2.8.0
├── commander@2.19.0
├─┬ config-yml@0.10.3
├─┬ debug@2.6.9
├── es6-promise@3.3.1
├─┬ object.assign@4.1.0
├─┬ onoff@4.0.0
├─┬ rangeslider.js@2.3.2
├─┬ serialport@7.1.5
└─┬ xml-js@1.6.11



pi@raspberrypi:~ $ npm list
/home/pi
├─┬ bleno@0.5.0
├── ejs@2.6.1
├─┬ express@4.16.4
├── q@1.5.1
├─┬ socket.io@2.2.0
└─┬ xml-js@1.6.11

With best regards
Michael

**Comment by weinzmi** [comment]
Hi choucous,
You posted this issue at 360manu‘s projectpage, but you are mentioning the fork  „daumUSB2BLE“.

What release/project are we talking about?

**Comment by choucous** [comment]
Tank you at all.
My answer in the right project page „daumUSB2BLE“
